// Code generated by go generate; DO NOT EDIT.

package mago

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

const (
	ExpectedMiniaudioVersionMajor    uint32             = 0
	ExpectedMiniaudioVersionMinor    uint32             = 11
	ExpectedMiniaudioVersionRevision uint32             = 25
	Success                          Result             = 0
	Error                            Result             = -1
	InvalidArgs                      Result             = -2
	OutOfMemory                      Result             = -4
	NoBackend                        Result             = -203
	NoDevice                         Result             = -204
	InvalidDeviceConfig              Result             = -206
	DeviceNotInitialized             Result             = -300
	DeviceAlreadyInitialized         Result             = -301
	DeviceNotStarted                 Result             = -302
	DeviceNotStopped                 Result             = -303
	BackendWASAPI                    Backend            = 0
	BackendDSound                    Backend            = 1
	BackendWinMM                     Backend            = 2
	BackendCoreAudio                 Backend            = 3
	BackendSndIO                     Backend            = 4
	BackendAudio4                    Backend            = 5
	BackendOSS                       Backend            = 6
	BackendPulseAudio                Backend            = 7
	BackendALSA                      Backend            = 8
	BackendJACK                      Backend            = 9
	BackendAAudio                    Backend            = 10
	BackendOpenSL                    Backend            = 11
	BackendWebAudio                  Backend            = 12
	BackendCustom                    Backend            = 13
	BackendNull                      Backend            = 14
	DeviceTypePlayback               DeviceType         = 1
	DeviceTypeCapture                DeviceType         = 2
	DeviceTypeDuplex                 DeviceType         = 3
	DeviceTypeLoopback               DeviceType         = 4
	ShareModeShared                  ShareMode          = 0
	ShareModeExclusive               ShareMode          = 1
	PerformanceProfileLowLatency     PerformanceProfile = 0
	PerformanceProfileConservative   PerformanceProfile = 1
	FormatUnknown                    Format             = 0
	FormatU8                         Format             = 1
	FormatS16                        Format             = 2
	FormatF32                        Format             = 5
	NotificationStarted              NotificationType   = 0
	NotificationStopped              NotificationType   = 1
	NotificationRerouted             NotificationType   = 2
	NotificationInterruptionBegan    NotificationType   = 3
	NotificationInterruptionEnded    NotificationType   = 4
	NotificationUnlocked             NotificationType   = 5
)

type bindingSet struct {
	maVersion                 func(*uint32, *uint32, *uint32)
	maVersionString           func() string
	maResultDescription       func(Result) string
	maContextInit             func(*Backend, uint32, unsafe.Pointer, *contextHandle) Result
	maContextUninit           func(*contextHandle)
	maContextEnumerateDevices func(*contextHandle, uintptr, uintptr) Result
	magoDeviceInit            func(*contextHandle, *deviceConfigNative, **deviceHandle) Result
	magoDeviceUninitFree      func(*deviceHandle)
	maDeviceStart             func(*deviceHandle) Result
	maDeviceStop              func(*deviceHandle) Result
	maDeviceGetState          func(*deviceHandle) DeviceState
	maDeviceGetName           func(*deviceHandle, DeviceType, *byte, uintptr, *uintptr) Result
	maDeviceGetInfo           func(*deviceHandle, DeviceType, *deviceInfoNative) Result
	maDeviceGetLog            func(*deviceHandle) *logHandle
	maDeviceGetContext        func(*deviceHandle) *contextHandle
	maDeviceSetMasterVolume   func(*deviceHandle, float32) Result
	maDeviceGetMasterVolume   func(*deviceHandle, *float32) Result
	maDeviceSetMasterVolumeDB func(*deviceHandle, float32) Result
	maDeviceGetMasterVolumeDB func(*deviceHandle, *float32) Result
	maContextGetLog           func(*contextHandle) *logHandle
	maContextGetDeviceInfo    func(*contextHandle, DeviceType, unsafe.Pointer, *deviceInfoNative) Result
	magoAlloc                 func(int32) unsafe.Pointer
	magoFree                  func(unsafe.Pointer)
	maLogInit                 func(unsafe.Pointer, *logHandle) Result
	maLogUninit               func(*logHandle)
	maLogPost                 func(*logHandle, uint32, string) Result
	maLogLevelToString        func(uint32) string
	magoLogRegisterCallback   func(*logHandle, uintptr, uintptr) Result
	magoLogUnregisterCallback func(*logHandle, uintptr, uintptr) Result
	magoContextConfigInit     func(unsafe.Pointer)
	magoContextConfigSetLog   func(unsafe.Pointer, *logHandle)
}

func (b *bindingSet) register(handle uintptr) {
	purego.RegisterLibFunc(&b.maVersion, handle, "ma_version")
	purego.RegisterLibFunc(&b.maVersionString, handle, "ma_version_string")
	purego.RegisterLibFunc(&b.maResultDescription, handle, "ma_result_description")
	purego.RegisterLibFunc(&b.maContextInit, handle, "ma_context_init")
	purego.RegisterLibFunc(&b.maContextUninit, handle, "ma_context_uninit")
	purego.RegisterLibFunc(&b.maContextEnumerateDevices, handle, "ma_context_enumerate_devices")
	purego.RegisterLibFunc(&b.magoDeviceInit, handle, "mago_device_init")
	purego.RegisterLibFunc(&b.magoDeviceUninitFree, handle, "mago_device_uninit_free")
	purego.RegisterLibFunc(&b.maDeviceStart, handle, "ma_device_start")
	purego.RegisterLibFunc(&b.maDeviceStop, handle, "ma_device_stop")
	purego.RegisterLibFunc(&b.maDeviceGetState, handle, "ma_device_get_state")
	purego.RegisterLibFunc(&b.maDeviceGetName, handle, "ma_device_get_name")
	purego.RegisterLibFunc(&b.maDeviceGetInfo, handle, "ma_device_get_info")
	purego.RegisterLibFunc(&b.maDeviceGetLog, handle, "ma_device_get_log")
	purego.RegisterLibFunc(&b.maDeviceGetContext, handle, "ma_device_get_context")
	purego.RegisterLibFunc(&b.maDeviceSetMasterVolume, handle, "ma_device_set_master_volume")
	purego.RegisterLibFunc(&b.maDeviceGetMasterVolume, handle, "ma_device_get_master_volume")
	purego.RegisterLibFunc(&b.maDeviceSetMasterVolumeDB, handle, "ma_device_set_master_volume_db")
	purego.RegisterLibFunc(&b.maDeviceGetMasterVolumeDB, handle, "ma_device_get_master_volume_db")
	purego.RegisterLibFunc(&b.maContextGetLog, handle, "ma_context_get_log")
	purego.RegisterLibFunc(&b.maContextGetDeviceInfo, handle, "ma_context_get_device_info")
	purego.RegisterLibFunc(&b.magoAlloc, handle, "mago_alloc")
	purego.RegisterLibFunc(&b.magoFree, handle, "mago_free")
	purego.RegisterLibFunc(&b.maLogInit, handle, "ma_log_init")
	purego.RegisterLibFunc(&b.maLogUninit, handle, "ma_log_uninit")
	purego.RegisterLibFunc(&b.maLogPost, handle, "ma_log_post")
	purego.RegisterLibFunc(&b.maLogLevelToString, handle, "ma_log_level_to_string")
	purego.RegisterLibFunc(&b.magoLogRegisterCallback, handle, "mago_log_register_callback")
	purego.RegisterLibFunc(&b.magoLogUnregisterCallback, handle, "mago_log_unregister_callback")
	purego.RegisterLibFunc(&b.magoContextConfigInit, handle, "mago_context_config_init")
	purego.RegisterLibFunc(&b.magoContextConfigSetLog, handle, "mago_context_config_set_log")
}

var _ unsafe.Pointer
