// Code generated by go generate; DO NOT EDIT.

package mago

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

const (
	ExpectedMiniaudioVersionMajor    uint32             = 0
	ExpectedMiniaudioVersionMinor    uint32             = 11
	ExpectedMiniaudioVersionRevision uint32             = 25
	Success                          Result             = 0
	Error                            Result             = -1
	InvalidArgs                      Result             = -2
	OutOfMemory                      Result             = -4
	NoBackend                        Result             = -203
	NoDevice                         Result             = -204
	InvalidDeviceConfig              Result             = -206
	DeviceNotInitialized             Result             = -300
	DeviceAlreadyInitialized         Result             = -301
	DeviceNotStarted                 Result             = -302
	DeviceNotStopped                 Result             = -303
	BackendWASAPI                    Backend            = 0
	BackendDSound                    Backend            = 1
	BackendWinMM                     Backend            = 2
	BackendCoreAudio                 Backend            = 3
	BackendSndIO                     Backend            = 4
	BackendAudio4                    Backend            = 5
	BackendOSS                       Backend            = 6
	BackendPulseAudio                Backend            = 7
	BackendALSA                      Backend            = 8
	BackendJACK                      Backend            = 9
	BackendAAudio                    Backend            = 10
	BackendOpenSL                    Backend            = 11
	BackendWebAudio                  Backend            = 12
	BackendCustom                    Backend            = 13
	BackendNull                      Backend            = 14
	DeviceTypePlayback               DeviceType         = 1
	DeviceTypeCapture                DeviceType         = 2
	DeviceTypeDuplex                 DeviceType         = 3
	DeviceTypeLoopback               DeviceType         = 4
	ShareModeShared                  ShareMode          = 0
	ShareModeExclusive               ShareMode          = 1
	PerformanceProfileLowLatency     PerformanceProfile = 0
	PerformanceProfileConservative   PerformanceProfile = 1
	FormatUnknown                    Format             = 0
	FormatU8                         Format             = 1
	FormatS16                        Format             = 2
	FormatF32                        Format             = 5
	NotificationStarted              NotificationType   = 0
	NotificationStopped              NotificationType   = 1
	NotificationRerouted             NotificationType   = 2
	NotificationInterruptionBegan    NotificationType   = 3
	NotificationInterruptionEnded    NotificationType   = 4
	NotificationUnlocked             NotificationType   = 5
)

type bindingSet struct {
	maVersion                   func(*uint32, *uint32, *uint32)
	maVersionString             func() string
	maResultDescription         func(Result) string
	magoContextInitDefault      func(**contextHandle) Result
	magoContextInitWithBackends func(*Backend, uint32, **contextHandle) Result
	magoContextUninitFree       func(*contextHandle)
	magoContextGetDevices       func(*contextHandle, **deviceInfoNative, *uint32, **deviceInfoNative, *uint32) Result
	magoContextFreeDeviceInfos  func(*deviceInfoNative)
	magoDeviceInitPlayback      func(*contextHandle, *playbackDeviceConfigNative, **deviceHandle) Result
	magoDeviceUninitFree        func(*deviceHandle)
	maDeviceStart               func(*deviceHandle) Result
	maDeviceStop                func(*deviceHandle) Result
}

func (b *bindingSet) register(handle uintptr) {
	purego.RegisterLibFunc(&b.maVersion, handle, "ma_version")
	purego.RegisterLibFunc(&b.maVersionString, handle, "ma_version_string")
	purego.RegisterLibFunc(&b.maResultDescription, handle, "ma_result_description")
	purego.RegisterLibFunc(&b.magoContextInitDefault, handle, "mago_context_init_default")
	purego.RegisterLibFunc(&b.magoContextInitWithBackends, handle, "mago_context_init_with_backends")
	purego.RegisterLibFunc(&b.magoContextUninitFree, handle, "mago_context_uninit_free")
	purego.RegisterLibFunc(&b.magoContextGetDevices, handle, "mago_context_get_devices")
	purego.RegisterLibFunc(&b.magoContextFreeDeviceInfos, handle, "mago_context_free_device_infos")
	purego.RegisterLibFunc(&b.magoDeviceInitPlayback, handle, "mago_device_init_playback")
	purego.RegisterLibFunc(&b.magoDeviceUninitFree, handle, "mago_device_uninit_free")
	purego.RegisterLibFunc(&b.maDeviceStart, handle, "ma_device_start")
	purego.RegisterLibFunc(&b.maDeviceStop, handle, "ma_device_stop")
}

var _ unsafe.Pointer
